import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.

                int kids =0;
                int two_kids_counter = 0;
                int three_kids_counter = 0;
                int four_or_more_counter = 0;

                for(int i = 0; i < T; i++){

                    Boolean boy = false;
                    Boolean girl = false;
                    int boy_count = 0;
                    int girl_count = 0;

                    while(!boy || !girl){

                        int random = (int)(Math.random() * 2);

                        if(random == 0){
                            boy_count ++;
                            boy = true;
                            }

                        if(random == 1){
                            girl_count ++;
                            girl = true;
                            }
                        }

                    int sum = boy_count + girl_count;
                    kids = kids + sum;

                    if(sum == 2){
                        two_kids_counter ++;
                        }

                    else{

                        if(sum == 3){
                        three_kids_counter ++;
                        }

                        else{
                            four_or_more_counter ++;
                            }
                    }





                }

            Double avarage = kids/(double)T;
            System.out.println("Average: "+ avarage + " children to get at least one of each gender.");
            System.out.println("Number of families with 2 children: " + two_kids_counter);
            System.out.println("Number of families with 3 children: " + three_kids_counter);
            System.out.println("Number of families with 4 or more children: " + four_or_more_counter);

        }
}
